### ISSUE TITLE
Searching for nothing brings up "null" in search results.

### ISSUE THREAD

**Issue by Deathstalkr1** [Frontesque/VueTube#100]
**Describe the bug**
Searching for nothing ends up searching as "null"

**To Reproduce**
1. Go to VueTube app
2. Search for nothing (as in no text).
3. Find out that it automatically searches for "null"

**Expected behavior**
Not bringing up search entry

**Screenshots**
![Screenshot_20220318-173300_VueTube.jpg](https://user-images.githubusercontent.com/100892324/159085916-69ddc337-a326-49e0-a747-737e9aab0983.jpg)

**Device Information**
 - OS: Android 12
 - App version: 1b6a9f4 
 - Device: Samsung SM-G998U

**Additional context**
None.

**Comment by PickleNik** [comment]
this makes the kind of sense that does

**Comment by DanWlker** [comment]
This should fix it for now, but could discuss if a popup that alerts the user to an empty search would be better.

**Comment by Frontesque** [comment]
Fixed in PR #117
