### ISSUE TITLE
Download Audio only

### ISSUE THREAD

**Issue by Featyre** [Frontesque/VueTube#11]
Downloading videos is possible, but why not download audio only?

**Comment by Frontesque** [comment]
This likely will cause legal issues with youtube. The download feature will be remove eventually too sadly.

**Comment by venkat2305** [comment]
use ymusic.io to download videos and audio , its simple. share the yt video to the app directly from the share page.
 lets not put this app at risk

**Comment by 404-Program-not-found** [comment]
Either use yt-dlp or newpipe
