### ISSUE TITLE
Rounded corner bug is still there

### ISSUE THREAD

**Issue by stevenfelix505** [Frontesque/VueTube#112]
**Describe the bug**
While i opening VueTube app and clicking the 🔍 search icon, i see the buggy rounded corner near navigation bar.

**To Reproduce**
1. Open VueTube app
2. Click on the 🔍 Search icon
3. See error

**Expected behavior**
We should not see the buggy black rounded corner near navigation bar.

**Screenshots**
Image 1 - Buggy Rounded Corner :
![Screenshot_20220319-201105_VueTube.jpg](https://user-images.githubusercontent.com/57618009/159122626-5b04f022-52b6-47dd-8b43-e86b1a2a4ab7.jpg)

Image 2 - About Screen :
![Screenshot_20220319-201121_VueTube.jpg](https://user-images.githubusercontent.com/57618009/159122640-3f7e2b65-317a-4dd3-8aa8-50c2aea3b256.jpg)

**Device Information**
 - OS: Android 11
 - App Version: 1b6a9f4

**Comment by DanWlker** [comment]
This is still being discussed on discord in the ui-votes section, so won't create a PR yet unless req. As there is talks for an option to disable or enable it.

**Comment by stevenfelix505** [comment]
Thank you for fixing this bug. Now i will close the issue.

Image 1 :
![Screenshot_20220323-134008_VueTube.jpg](https://user-images.githubusercontent.com/57618009/159639102-ff9c2413-4ca6-47f1-ba0d-5f759d0de7da.jpg)

Image 2 :
![Screenshot_20220323-134238_VueTube.jpg](https://user-images.githubusercontent.com/57618009/159639159-0b33513e-ef62-4351-b9ae-ca13d813b124.jpg)
