### ISSUE TITLE
Theme change breaks the about section

### ISSUE THREAD

**Issue by SadSpear** [Frontesque/VueTube#116]
**Describe the bug**
About section breaking after theme change until app restart

**To Reproduce**
1. Change theme
2. About section is broken

**Expected behavior**
About section should not break

**Screenshots**
[Screen record](https://www.youtube.com/watch?v=PoYDWVNU0MU)

**Device Information**
 - OS: Android 12
 - App Version ee78e75

**Comment by DanWlker** [comment]
So, upon further inspection. The class for "row" doesn't actually designate the flex direction of it's children. So a theme change might have triggered an overflow or unexpected behavior or smt (idk). The proposed solution is adding a style="flex-direction:column", which should make the elements consistent.

![image](https://user-images.githubusercontent.com/60170554/159205123-66055afb-a743-479d-b571-f9eb74663f36.png)

proposed fix:
![image](https://user-images.githubusercontent.com/60170554/159205192-9e28fa9a-8665-4dda-9f56-b71e2614edd4.png)

**Comment by DanWlker** [comment]
Changing the class from row to col could work as well but I'm not familiar with the class definition enough to confirm its behavior for all cases. Do advise if it is a good solution

**Comment by Frontesque** [comment]
Possibly fixed in #147

**Comment by SadSpear** [comment]
Seems fixed in d91b5de
