### ISSUE TITLE
Search not working for most terms.

### ISSUE THREAD

**Issue by Exw27** [Frontesque/VueTube#120]
**Describe the bug**
The search dose not work for most search terms even if you click the prompt.

**To Reproduce**
1. Click the search 
2. Write good hunter
3. Click the prompt
4. Nothing appears

**Expected behavior**
Videos should appear

**Device Information**
 - OS: Android 11
 - App Version 

**Screen record**
https://user-images.githubusercontent.com/51909835/159138402-264c8b2b-0dfd-4b44-a575-4fb1b9c3d3e8.mp4

**Comment by 404-Program-not-found** [comment]
fixed in #170
