### ISSUE TITLE
"Latest" and "Installed" buttons aren't aligned

### ISSUE THREAD

**Issue by ThatOneCalculator** [Frontesque/VueTube#122]
**Describe the bug**
![Screenshot_20220319-142322.jpg](https://user-images.githubusercontent.com/44733677/159138852-a908caea-d763-4a94-9c7a-8893c4a5f136.jpg)

**To Reproduce**
1. Install latest version
2. Go to updates

**Device Information**
 - OS: Android 11
 - App Version 35f5fff

**Comment by DanWlker** [comment]
Fixed in commit https://github.com/Frontesque/VueTube/commit/22f999f9c36e4e9c2a33dbc127c6ee13be8b6cf2
