### ISSUE TITLE
The app it stays "loading"

### ISSUE THREAD

**Issue by Menorah** [Frontesque/VueTube#124]
**Describe the bug**
None of the beta versions work on android 5.1.1. When I open the app it stays "loading" (it only shows the loading circle).

**To Reproduce**
1. Open the app.

**Expected behavior**
The page should be displayed.

**Device Information**
 - OS: Android 5.1.1
 - App Version: 1.0

**Comment by 404-Program-not-found** [comment]
is it specifically on android 5.1.1 or can other devices replicate the error?

**Comment by Menorah** [comment]
I have only tested it on Android 5.1.1.

**Comment by 404-Program-not-found** [comment]
What's your app version code? It should be shown under settings > about > app version

**Comment by Menorah** [comment]
35f5fff

**Comment by Frontesque** [comment]
> I have only tested it on Android 5.1.1.

ill test on my android 5 device

**Comment by Frontesque** [comment]
I can't seem to reproduce. Could you provide a screen recording?
![image](https://user-images.githubusercontent.com/27463495/159165494-afec59cd-32ad-4d89-bf39-448daee7dcb6.png)
>> Device Information
> Android: 5.0.2
> Model: SM-G925V (Galaxy S6 Edge)
> Manufacturer: Samsung
> Virtual: No

**Comment by nokanol45** [comment]
Can confirm home screen does not load on Android 5.1.1:
![Screenshot_2022-03-20-23-08-21](https://user-images.githubusercontent.com/101823676/159169054-745f3194-2b9b-4669-8633-a10692db6fa3.png)

Here are screenshots of the logs:
![Screenshot_2022-03-20-23-03-14](https://user-images.githubusercontent.com/101823676/159168916-5265ec0c-2a9d-471d-ab70-00ebbdb70faa.png)
![Screenshot_2022-03-20-23-03-25](https://user-images.githubusercontent.com/101823676/159168919-6e872ecc-9b4f-4d60-ab95-cb048ad3e671.png)
![Screenshot_2022-03-20-23-03-30](https://user-images.githubusercontent.com/101823676/159168920-8b55efd9-a21f-4000-8932-22e0e1ae467c.png)

> Device Info:
> Android: 5.1.1
> Model: SM-J500F (Samsung Galaxy J5)
> Manufacturer: Samsung
> Virtual: No

**Comment by Menorah** [comment]
> I can't seem to reproduce. Could you provide a screen recording? ![image](https://user-images.githubusercontent.com/27463495/159165494-afec59cd-32ad-4d89-bf39-448daee7dcb6.png)
> 
> > Device Information~
> > Android: 5.0.2
> > Model: SM-G925V (Galaxy S6 Edge)
> > Manufacturer: Samsung
> > Virtual: No


https://user-images.githubusercontent.com/8613069/159175156-2e5a2fce-2e10-4afd-9631-35da079a23e7.mp4

**Comment by Frontesque** [comment]
Try the latest unstable build from our site, it may fix it since I changed a lot of loading stuff

https://vuetube.app/install/

**Comment by nokanol45** [comment]
Updating Android System Webview makes it work for me:

**Comment by Frontesque** [comment]
The cause of this bug is that your Android System WebView version is out of date. I just updated our documentation on this so hopefully, it can help you!

https://vuetube.app/install/android-system-webview

**Comment by Menorah** [comment]
Solved. Thanks!
