### ISSUE TITLE
Unable to Find Download Link to APK

### ISSUE THREAD

**Issue by sileeb** [Frontesque/VueTube#128]
I've so far downloaded the source cod which is not what I want. So where do I download the apk?

**Comment by 404-Program-not-found** [comment]
- go to the following [page](https://github.com/Frontesque/VueTube/actions)
- click into one of the links that has a green tick
- scroll down
- find the file labeled android

OR

- go to the [discord server](https://discord.gg/RegzKjQNz2)
- go to #apk
- download the latest nightly build

**Comment by sileeb** [comment]
I found it and installed it. But its very basic and theres not much functionality.. why is that?

**Comment by 404-Program-not-found** [comment]
the app has just started development very recently, so we haven't had much of a chance to implement all the features

**Comment by sileeb** [comment]
Oh I see. I understand now. Well I know CSS so in case you need someone to help out let me know. And thank you Alex!
