### ISSUE TITLE
Cannot select recommendations while watching a current video

### ISSUE THREAD

**Issue by Nebula6531** [Frontesque/VueTube#135]
**Describe the bug**
If you are watching a video and what to click on the Reccomendations listed below it, nothing happens when you click one 

**To Reproduce**
1. Go to VueTube
2. Click on a video or search for one and start playing it
3. Scroll down to the reccomendations listed below the video and try to play it 

**Expected behavior**
The new video that is clicked on should play 

**Screenshots**
![Screenshot_20220320-130707](https://user-images.githubusercontent.com/79540507/159163865-ee3b55c2-976d-4492-b66c-47b1cfebe323.jpg)

**Device Information**
 - OS: Android 11
 - App Version c79dbf7

**Comment by etekweb** [comment]
Fixed in pull request #160
