### ISSUE TITLE
The entire interface stretches when the end is reached

### ISSUE THREAD

**Issue by SadSpear** [Frontesque/VueTube#14]
**Describe the bug**
When scrolling and reaching the end, the entire interface stretches.

**To Reproduce**
1. Go in the update page
2. Scroll up to hit the end
3. The entire interface will stretch

**Expected behavior**
Only the scrollable part should have the stretch effect. Not the top and bottom bar.

**Screenshots**
[Screen recording](https://youtu.be/JwtZE6DygkA)

**Device Information**
 - OS: Android 12
 - App Version 5db855a

**Comment by PickleNik** [comment]
Fixed that, will update with PR tomorrow 🚀 :)
