### ISSUE TITLE
Thumbnail not visible for some videos

### ISSUE THREAD

**Issue by AbhinavSinghG** [Frontesque/VueTube#143]
**Describe the bug**
Encountered some videos with thumbnail like of restricted videos even though videos can be played without any problem.

**To Reproduce**
Scroll through recommendations.

**Screenshots**
![Screenshot_2022-03-20-22-17-03-98_af8db8b84e960dcc6ad6c0315e12614a.jpg](https://user-images.githubusercontent.com/101918870/159174012-7c087a1e-eec3-495d-a5a3-fa39c0a33656.jpg)

![Screenshot_2022-03-20-14-26-20-85_af8db8b84e960dcc6ad6c0315e12614a.jpg](https://user-images.githubusercontent.com/101918870/159174024-e0cbab2b-8e8b-421e-8217-02d6f49e4018.jpg)

**Device Information**
 - OS: [Android 11]
 - App Version [1.0]

**Comment by 404-Program-not-found** [comment]
Already wrote a fix for it, will release the patch in my next PR

**Comment by 404-Program-not-found** [comment]
addressed in #150. Can someone close this?

**Comment by Frontesque** [comment]
> 404-Program-not-found

Sure thing, also check your email inbox.
