### ISSUE TITLE
Age verification bypass

### ISSUE THREAD

**Issue by ghost** [Frontesque/VueTube#144]
Based on what NewPipe devs already do with theirs extractor: https://github.com/TeamNewPipe/NewPipeExtractor/pull/665

**Comment by NexMaxu** [comment]
But the age verification is "already here" because it's a custom player, you can test if you want.

**Comment by 404-Program-not-found** [comment]
I have checked - age restricted videos from youtube cannot be played without logging in

**Comment by TriDyE** [comment]
You can try with this video:

https://m.youtube.com/watch?v=EX_8ZjT2sO4&feature=youtu.be

I can confirm that in NewPipe, after enabling the option to watch restricted videos, it works well.

**Comment by PickleNik** [comment]
#214 mentioned [this GreasyFork script](https://greasyfork.org/en/scripts/423851-simple-youtube-age-restriction-bypass)

**Comment by 404-Program-not-found** [comment]
There's this bypass from NewPipe https://github.com/TeamNewPipe/NewPipe/issues/8102

**Comment by goodandrewsoft** [comment]
How enable option for play age restricted video in newpipe?

**Comment by 404-Program-not-found** [comment]
> How enable option for play age restricted video in newpipe?

this isn't the Newpipe development team. You will find better luck in asking in their repo instead

**Comment by Frontesque** [comment]
> However it should be noted that Age verification bypassing is something that will break very often.

For this reason, I suggest that we leave it up to the community (or one of our devs) to make an independent plugin for the app, not something that is built-in stock.
