### ISSUE TITLE
Please Add This Feature.

### ISSUE THREAD

**Issue by max5354** [Frontesque/VueTube#149]
Feature request.
1) add option to use custom equalizer in setting
2) add option to bookmark a playlist (like newpipe does)
3) import youtube playlists
4) add comment section
5) add option to change bitrate of song i  Setting ( like 128kbps, 256 kbps.)
6) add lyrics option 
7) add option to turn on captions
8) like/unlike thumb for youtube videos
9) add default play in setting that show (mp3 or mp4) this option already in ymusic app
10) will you add "strech overacroll" in whole app
11) light mode/ dark mode 
12)add option to hide status bar
13) pause on headset disconnect and resume on headset connect
14) double press to next video or song in wired headset 
15) tripple press to previous video or song in wired headset
16) add repeat option in now playing screen 
17)  add shuffle option
18) add sleep timer
19) add option in setting to customize corners of video ( rounded corner thumbnails and more rounded corner thumbnails)
20) resume after call
21) fade play/pause
22) fade when seek
23) swipe control for brightness and volume control whenever we play video in landscape mode
24) double to seek video in landscape mode

**Comment by L33Tech** [comment]
This is probably too much for one issue...

**Comment by Frontesque** [comment]
These should be individual issues

**Comment by Svk1190** [comment]
Many great points! Would be great if you could split them up into individual issues with more explanation for each feature. Also some of these features have already been requested, maybe just upvote those issues and comment on them.
