### ISSUE TITLE
RYD 

### ISSUE THREAD

**Issue by NSTAdventure** [Frontesque/VueTube#151]
**Is your feature request related to a problem? Please describe.**
i need find out video review / rate but google disabled dislike count

**Describe the solution you'd like**
Add [Return YouTube Dislike API](https://returnyoutubedislike.com/) 

**Describe alternatives you've considered**

**Additional context**
link provided click the blue text above
doc also there to help

**Comment by NotHuza** [comment]
> **Is your feature request related to a problem? Please describe.** i need find out video review / rate but google disabled dislike count
> 
> **Describe the solution you'd like** Add [Return YouTube Dislike API](https://returnyoutubedislike.com/)
> 
> **Describe alternatives you've considered**
> 
> **Additional context** link provided click the blue text above doc also there to help

This is aredy there

**Comment by Frontesque** [comment]
Already included

**Comment by NSTAdventure** [comment]
> Already included

bruh why marked as spam?????
that isn't my intention :-(
