### ISSUE TITLE
More Playback Speeds

### ISSUE THREAD

**Issue by 0gamesbookstore** [Frontesque/VueTube#16]
It would be great if VueTube had a feature like changing the playback speed of a video to x3 or x4 etc.

**Comment by Isssuemaker** [comment]
+1

**Comment by Svk1190** [comment]
Granular speed modification would be nice, for example X1.1, X1.2, X1.3 and so on (upto X4). Maybe a slider with a numeric entry option can be helpful. Two images showing a slider with numeric entry are given below as examples. 

![Alt Text](https://miro.medium.com/max/1294/1*htHTxtpn6u_kq7rdhaOR7w.gif)

![image](https://user-images.githubusercontent.com/12389625/158309321-ee0d10d0-595f-412a-b6ce-4204c6a2e362.png)

**Comment by FarzeenAhmed** [comment]
+1
