### ISSUE TITLE
Migrate to Vue 3 and TypeScript

### ISSUE THREAD

**Issue by NatoBoram** [Frontesque/VueTube#165]
**Is your feature request related to a problem? Please describe.**

I'd like to contribute a few lines of code sometimes, but the app is using [Vue 2](https://github.com/Frontesque/VueTube/blob/main/NUXT/package.json#L17) and JavaScript. Since I don't know Vue, I'd like to learn the latest version instead of a deprecated one.

**Describe the solution you'd like**

Migrate to Vue 3 and TypeScript

**Describe alternatives you've considered**

**Additional context**

Vue 3 is the default since February: https://blog.vuejs.org/posts/vue-3-as-the-new-default.html

Since it's a fairly new project using a fairly new framework, it would be appropriate to use a fairly new version of the framework.

**Comment by Frontesque** [comment]
> I'd like to contribute a few lines of code sometimes, but the app is using [Vue 2](https://github.com/Frontesque/VueTube/blob/main/NUXT/package.json#L17) and JavaScript. Since I don't know Vue, I'd like to learn the latest version instead of a deprecated one.

Vue 2 is the latest version that NUXT supports, so we can't upgrade since NUXT is how we are managing our codespace.
