### ISSUE TITLE
Search results only show results from "People also watched" category

### ISSUE THREAD

**Issue by nokanol45** [Frontesque/VueTube#172]
**Describe the bug**
When searching in the app, only results from the category "People also watched" are shown, thus the actual top result (the relevant ones) aren't shown.
**To Reproduce**
1. search any term in the app (in my example: rush e)
2. search the same term in an incognito tab on a browser
3. see that only results from the category "People also watched" are shown on the app

**Expected behavior**
All results from the incognito browser tab should also appear in the app.

**Screenshots**

Screenshot of the app results:
![Screenshot_20220323-234512_VueTube](https://user-images.githubusercontent.com/101823676/159741068-e8eacdb3-87b5-43dd-a942-9fb0d66c24e0.jpg)

Screenshot of the "People also watched" category in the incognito browser tab. Notice the similarities in the results:
![results_that_appears_in_the_app](https://user-images.githubusercontent.com/101823676/159741321-73236924-f33c-4697-ab39-898d74713e62.jpeg)

Screenshot of the first results in the incognito browser tab:
![results_that_should_appear](https://user-images.githubusercontent.com/101823676/159741258-84daf479-ef2f-4dd1-be23-19c07d7d2bea.jpeg)

**Device Information**
App version: de3d8a7
Android version: 12 (One UI 4.0)
Device: Galaxy S10 (Model no. SM-G9730)
![Screenshot_20220323-235142_VueTube](https://user-images.githubusercontent.com/101823676/159741032-d3e15bef-25fe-4b23-a35d-5cef7b0bc8c5.png)

**Additional Context**
This bug was not present before #170 , i.e. when the search switched to using innertube API instead of html scraping (I think). So build 66a0827 works as intended:

Screenshot of build 66a0827 showing the correct results:
![Screenshot_20220324-000207_VueTube](https://user-images.githubusercontent.com/101823676/159743421-d0ae7b5f-1d15-438a-b65d-990374c2982b.jpg)

**Comment by Frontesque** [comment]
I have noticed that too but I didn't realize that it was coming from the "people also watched" section.

**Comment by 404-Program-not-found** [comment]
I'll push a fix in a short while

**Comment by 404-Program-not-found** [comment]
fixed in PR #178. Closing
