### ISSUE TITLE
[BUG] Opening app for the first time will be fully white

### ISSUE THREAD

**Issue by MatadorProBr** [Frontesque/VueTube#185]
**Describe the bug**
When trying to open the app, it's just everything white and nothing else.

**To Reproduce**
1. Open 'VueTube' for the first time
2. See error

**Expected behavior**
The app should work and open normally without being fully white.

**Screenshots**
![image](https://user-images.githubusercontent.com/71022656/160013312-fc44a905-cfe5-4c34-b804-fd9d7caf17dd.png)

**Device Information**
 - OS: [Android 10]
 - App Version [Latest Nightly]

**Additional context**
After you ask, yes, I already have the latest WebView update installed from the Play Store.

**Comment by 404-Program-not-found** [comment]
was this bug experienced in previous nightly releases?

**Comment by MatadorProBr** [comment]
> was this bug experienced in previous nightly releases?

Nope. But the previous nightly releases that I used, It didn't have the videos, home and search videos feature yet

**Comment by 404-Program-not-found** [comment]
> > was this bug experienced in previous nightly releases?
> 
> Nope. But the previous nightly releases that I used, It didn't have the videos, home and search videos feature yet

that would have been a long time ago. Can you check if you are able to run the march 23rd build?

**Comment by MatadorProBr** [comment]
> that would have been a long time ago. Can you check if you are able to run the march 23rd build?

This one? https://github.com/Frontesque/VueTube/actions/runs/2029510034

**Comment by 404-Program-not-found** [comment]
yeah sure that could work

**Comment by MatadorProBr** [comment]
Same thing but now, it appears the logo and the loading icon
![image](https://user-images.githubusercontent.com/71022656/160029677-568e65e1-099c-4e81-a9cb-fc8f7fd7c369.png)

**Comment by Frontesque** [comment]
> Same thing but now, it appears the logo and the loading icon

This indicates that it's having an issue handshaking with innertube

**Comment by MatadorProBr** [comment]
> This indicates that it's having an issue handshaking with innertube. Please ensure that your Android System WebView version is up to date. https://vuetube.app/install/android-system-webview

I already said on "Additional Context"

> After you ask, yes, I already have the latest WebView update installed from the Play Store.

**Comment by Frontesque** [comment]
> I already said on "Additional Context"

If you're on anything past Android 7, please make sure that Google Chrome is also up to date.

**Comment by MatadorProBr** [comment]
Actually nevermind, it still happens in the last version

**Comment by MatadorProBr** [comment]
Here are the versions of WebView and Chrome that are installed on my phone (to see if it helps)

WebView: 99.0.4844.73
Chrome: 99.0.4844.73

**Comment by MatadorProBr** [comment]
And for some magic reason it works again but now on the latest version so now I can close this issue definitely, thanks for the help and sorry for disturbing you (by opening and closing the issue)
