### ISSUE TITLE
"Resume Playlist" feature

### ISSUE THREAD

**Issue by MetalZealot** [Frontesque/VueTube#188]
Imagine you've been watching/listening to a YouTube playlist with hundreds of videos, on and off for the last week, listening to a few hours here and there.
In order to jump last video you were watching in such a large playlist, you're forced to scroll all the way down and hunt for it. Every single time. 
And no, clicking on the last video in your "Watch History" does not resume the playlist itself.

This makes returning to a playlist to continue from your last spot quite a chore every time. I'd love a feature that would give you the option to return you to your last spot in a playlist after you've stopped or exited.

**Comment by KarstenPH** [comment]
why did you close this very quickly? usually, GitHub feature requests only get closed when the feature itself gets added or the issue is resolved (like if the feature isn't possible to be added due to code complications or because it's impossible).

**Comment by Svk1190** [comment]
I think this would be a useful feature.
