### ISSUE TITLE
Links without 'http://' prefix aren't clickable

### ISSUE THREAD

**Issue by BASEFlow1** [Frontesque/VueTube#212]
**Describe the bug**
Links without 'http://' prefix not clickable

**To Reproduce**
1. Find video with a link with missing 'http://' prefix in the description
2. Try clicking said link
3. Fail

**Expected behavior**
All links should be clickable

**Screenshots**
![Screenshot_20220330-172113_VueTube.jpg](https://user-images.githubusercontent.com/67925673/160871379-da55541e-2540-4acc-b411-228fee06bfb3.jpg)
Only the lower link is clickable, but both are highlighted in red

**Device Information**
 - OS: Android 12
 - App Version: 8ed5829

**Additional context**
App is the latest nightly release from the discord as of right now.

**Comment by 404-Program-not-found** [comment]
should be fixed now in #219
