### ISSUE TITLE
"installed" indicator in updates clips into date

### ISSUE THREAD

**Issue by starchyunderscore** [Frontesque/VueTube#215]
**Describe the bug**
when on the updates page, the green "installed" indicator clips into the date on the latest version.

**To Reproduce**
1. Be on latest version
2. Go to settings
3. Click on updates

**Expected behavior**
"installed" indicator does not clip into date

**Screenshots**
4d77e15 when it was current:
![Screenshot_20220331-180623_VueTube.jpg](https://user-images.githubusercontent.com/102399926/161157479-adc8180b-edfa-43aa-8de9-97200572180c.jpg)
58be0e4:
![Screenshot_20220331-232307_VueTube.jpg](https://user-images.githubusercontent.com/102399926/161189333-84fb04ce-a6bf-4347-9d93-bcf81005ab7c.jpg)

**Device Information**
 - OS: android 11
 - Device: SM-A102U
 - App Version 4d77e15 , 58be0e4

**Additional context**
this does not happen if you are not on the latest version, as the indicator can be on the correct line, as seen below:
downgraded to 8ed5829 while 4d77e15 was latest:
![Screenshot_20220331-181540_VueTube.jpg](https://user-images.githubusercontent.com/102399926/161158790-fef7fb9c-4409-4492-a82a-6bc35180392d.jpg)
4d77e15 after later releses:
![Screenshot_20220331-232741_VueTube.jpg](https://user-images.githubusercontent.com/102399926/161189699-e0d907c2-4982-4c38-b9af-40485806a0f5.jpg)
58be04 after april fools update:
![Screenshot_20220401-141343_VueTube.jpg](https://user-images.githubusercontent.com/102399926/161319554-c6d45cf9-e8b6-4213-bea9-5aec877a18fd.jpg)

**Comment by Frontesque** [comment]
This should be fixed now
