### ISSUE TITLE
Short Video Width Problem

### ISSUE THREAD

**Issue by EmreKara5aya** [Frontesque/VueTube#217]
**Describe the bug**
YouTube Short video width problem when scrolling down. Example: Bizimle Bir Yeteneğini Paylaş https://youtu.be/71Nye2CwXF8

**Screenshots**

![Screenshot_20220401_111830_com.Frontesque.youtube.jpg](https://user-images.githubusercontent.com/9382037/161224158-6b039da4-6c63-42ab-a6ec-66e287fa7ec8.jpg)

**Device Information**
 
![Screenshot_20220401_111917_com.Frontesque.youtube.jpg](https://user-images.githubusercontent.com/9382037/161224239-dd780cf7-706b-413c-af86-a37c247936a5.jpg)

**Comment by starchyunderscore** [comment]
it seems to also do that with normal videos on a tablet style android version

- android 7.1.2
- SM-G970N
- version 697ce5f
- emulated with ldplayer

![image](https://user-images.githubusercontent.com/102399926/162089336-f0c5987d-9437-4491-b593-076846ec118a.png)

**Comment by 404-Program-not-found** [comment]
fixed in #239
