### ISSUE TITLE
Add Newpipe feature that can be added

### ISSUE THREAD

**Issue by Isssuemaker** [Frontesque/VueTube#22]
Add Newpipe feature that can be added like download video to gallery plus I also want to be contributer for project can you add me as a contributer

**Comment by ArjixWasTaken** [comment]
What kind of shitty issue is this?
I am not even related to this repo and I already feel sorry for the dev.

If you want to be a contributor, you must contribute, the dev can't make you a contributor if you don't contribute.
I assume that this is basic knowledge, but I guess ignorant people exist everywhere.

"Add Newpipe feature that can be added", this sentence makes zero sense, can you even speak English?
Why can't you simply ask for "the ability to download videos"?

Anyways, enough ranting from me, good luck dev!

**Comment by PickleNik** [comment]
lmfao
