### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by RadiusGauge** [Frontesque/VueTube#222]
Hi.

Few days ago I posted a feature request about system-based automatic theme change. A developer of this project added the wontfix tag and the request was closed.

So I did a bit of research the same day on the NewPipe page (which has already got this feature) and I found a reference in the comments of a same request. Maybe it can be useful to you?

https://github.com/TeamNewPipe/NewPipe/pull/3632

**Comment by Frontesque** [comment]
Newpipe is written in java, VueTube is written in JavaScript. The name is similar but that's about it. They're very different languages with very different limitations. I'll look into it but i doubt any progress will be made
