### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by RadiusGauge** [Frontesque/VueTube#224]
Hi.

I was thinking that it would be useful to implement a dynamic UI, in order to make it compatible with Android TV devices.

So, for example, a different homepage visualization (grid instead list) or a more "TV remote like" commands.

**Comment by Frontesque** [comment]
maybe in the future. we are focusing on core youtube features first. I also don't have an android tv to test this on.

**Comment by Frontesque** [comment]
In the meantime, you can use this app
https://github.com/yuliskov/SmartTubeNext
