### ISSUE TITLE
Specific warnings

### ISSUE THREAD

**Issue by RadiusGauge** [Frontesque/VueTube#225]
Hi.

Since the possibility of installing plugins has been introduced, it would be useful to add some warning messages related to the main missing features.

For example showing an information window, if a user try to watch a restricted video or would give a look to the dislikes (I assume this will also become a plugin).

**Comment by RadiusGauge** [comment]
The request is related to the error messages, which should be clearer.

For example the one when you try to view an age-restricted video. The currently is: "error: item not found".

It's not clear enough imho.

**Comment by Frontesque** [comment]
this is an issue with YouTube's API, not our app
