### ISSUE TITLE
Region changer

### ISSUE THREAD

**Issue by venkat2305** [Frontesque/VueTube#234]
Can you add an option to change the region so we don't have to use a vpn to watch geolocked content.

**Comment by KarstenPH** [comment]
i could actually see a use case for this, i don't know how stuff works but i assume proxies could change your IP address and your location, and to actually get the regions where the content isn't blocked, it tries to look for the locations listed in the copyright claim (if it were actually accessible via the API, but im not sure if this is actually feaseable)

**Comment by 404-Program-not-found** [comment]
that would be impossible - it would require actual proxy infrastructure, that would be servers across the world.
