### ISSUE TITLE
Incomplete shows when opening the app

### ISSUE THREAD

**Issue by ShadowHunterKK** [Frontesque/VueTube#24]
**Describe the bug**
I installed VueTube latest stable build on my phone. And every main screen says Incomplete

**To Reproduce**
1. Open VueTube

**Expected behavior**
I should see the videos I guess

**Screenshots**
![Screenshot_20220314-153454_VueTube.png](https://user-images.githubusercontent.com/60347401/158183273-83e803c0-cfdc-4f82-be9f-a2948d15b957.png)
![Screenshot_20220314-153751_Settings.png](https://user-images.githubusercontent.com/60347401/158183469-ec941a6d-3165-4a61-8d34-137db57d41a4.png)

**Device Information**
 - OS: Droid On Time 5.2.1 Android 11
 - App Version Shows Version 1.0 in settings. In app menu is 6ff5c51.

**Comment by dausruddin** [comment]
Hi. I assume you solved this issue? Can you share how did you fix it? I'm getting the same problem.

**Comment by ShadowHunterKK** [comment]
> Hi. I assume you solved this issue? Can you share how did you fix it? I'm getting the same problem.

If u read the discord FAQ( which I did not before creating this) you will see that it is still a project. Its not usable yet. They said it may take 1-2 months

**Comment by dausruddin** [comment]
I see.

I saw someone commenting somewhere saying this app got potential. I thought it is already usable.

Thanks a lot for your reply :)

**Comment by ShadowHunterKK** [comment]
> I see.
> 
> I saw someone commenting somewhere saying this app got potential. I thought it is already usable.
> 
> Thanks a lot for your reply :)

No probs :)

**Comment by megapro17** [comment]
> If u read the discord FAQ( which I did not before creating this) you will see that it is still a project.

What a fuck I need to join a discord server to get this information??? Write this in the BEGINNING with big letters in the readme file

**Comment by ShadowHunterKK** [comment]
> > If u read the discord FAQ( which I did not before creating this) you will see that it is still a project.
> 
> What a fuck I need to join a discord server to get this information??? Write this in the BEGINNING with big letters in the readme file

He will do that. Mate, if I am right the project has around 4 days since it started.
