### ISSUE TITLE
APKs refuse to invoke package manager UI

### ISSUE THREAD

**Issue by MiningMarsh** [Frontesque/VueTube#257]
**Describe the bug**
All current releases of VueTube fail to open the android package manager UI and thus can't be easily installed.

Opening a terminal on the phone and manually installing it via `pm install VueTube.apk` works as expected.

**To Reproduce**
1. Download any VueTube APK
2. Navigate to device's download folder
3. Touch/click on the VueTube APK
4. Nothing happens

**Expected behavior**
The package manager UI shows with a window asking if you'd like to install or update VueTube.

**Device Information**
 - OS: Android 12.1, ArrowOS for Poco F3
 - App Version: Any tested (latest tested is April 6 Nightly)

**Additional context**
All other APKs work fine on this device, I don't believe this is the fault of the device.

**Comment by Frontesque** [comment]
Works for me. Please include a video of this happening along with what file manager you're using.

**Comment by MiningMarsh** [comment]
I have a video of this happening, but then a few minutes later something happened and it's working now.

I was just using the regular discord or files app, finally opened the APK in Firefox and that triggered something and both discord and the built-in android files app correctly install the APK.

I'm concluding this really is an obscure ROM bug, my bad.
