### ISSUE TITLE
rounded corners option annoyance

### ISSUE THREAD

**Issue by starchyunderscore** [Frontesque/VueTube#267]
**Describe the bug**
when on the election for how tounded corners should be, if you hold the slider somewhere between not at all and the first rounded option for any amount of time, such as if moving the slider slowly, it rapidly switches between the two.

**To Reproduce**
1. Go to settings
2. Click on ui tweaker
3. go to rounded corners option
4. slide slowly from all the way to the left over towards the right
5. See error

**Expected behavior**
the rounded corners option does not rapidly switch

**Screenshots**
https://youtu.be/5L6npFxoMH8
skip to 0:42

**Device Information**
![Screenshot_20220505-202348_VueTube.jpg](https://user-images.githubusercontent.com/102399926/167047761-6b22eae1-e072-4a05-bebd-bec55e50890e.jpg)

**Additional context**
labeled an annoyance in the title because thats all it really is

mabye make the corners not change untuill you lift your finger as a solution?

**Comment by 404-Program-not-found** [comment]
fixed in the latest unstable. Closing.
