### ISSUE TITLE
Material You theming support

### ISSUE THREAD

**Issue by NULL0404** [Frontesque/VueTube#37]
**Is your feature request related to a problem? Please describe.**
Extra system integration is always nice, a setting to make the app follow material you colors instead of the default would be a nice feature to see later on.

**Describe the solution you'd like**
Add a setting in appearance to follow material you theming, and change colors accordingly.

**Describe alternatives you've considered**
Color picker

**Additional context**
N/A

**Comment by Robotition** [comment]
This was already mentioned that it would be added in the future.
