### ISSUE TITLE
NFT Implementation ETA? 

### ISSUE THREAD

**Issue by G4Designs** [Frontesque/VueTube#42]
_Just kidding._ I look forward to the future of this project. Thank you for the hard work thus far. With Sponsorblock, Google sign-in, and a clean interface, I'll be completely on board.

**Comment by Dasnap** [comment]
Really I think we need an option to hide any video with NFT in the title...

**Comment by Frontesque** [comment]
> Really I think we need an option to hide any video with NFT in the title...

Although this was a joke issue, I could probably add a "blacklist" for words in video titles.

**Comment by ThatOneCalculator** [comment]
Every time you watch a video it mints it as an NFT :trollface:
