### ISSUE TITLE
Discord invalid invite

### ISSUE THREAD

**Issue by raluvy95** [Frontesque/VueTube#61]
As the title says. I unable to find other links to Discord server in README.md other than the badger.

**Comment by raluvy95** [comment]
![Screenshot_20220316-135707_Kiwi Browser](https://user-images.githubusercontent.com/43247023/158584900-63cb3569-3be8-4dbf-8ef1-dc05f3ec7058.jpg)
It still says deleted or invalid. Maybe discord is drunk for me.

**Comment by ForgottenHero** [comment]
Seems to work fine for me?
Might be an issue on your end sorry.
![Screenshot_2022-03-17-00-32-28-032_com discord](https://user-images.githubusercontent.com/4233945/158614042-861573a9-44a4-4529-a852-bc374d6079ec.jpg)

**Comment by Razuuu** [comment]
> 

try with private tab

**Comment by raluvy95** [comment]
Works with private tab, thanks! Discord really messed up and I have no idea anyway
