### ISSUE TITLE
Blocktube Integration in the app (Block videos and channels with a whitelist filter)

### ISSUE THREAD

**Issue by Trainerbob23** [Frontesque/VueTube#65]
Hello, I know it is not your top priority right now, but I want a video blocker for your video client. That is because I think it would be super useful for a lot of things. I think it would be great if you added to the app. And here is an example: please add this in the future or earlier please and thank you.
![Screenshot_20220316-135237](https://user-images.githubusercontent.com/101745219/158668504-7ed53f92-5a13-4119-b344-0840d3554c74.jpg)

**Comment by Frontesque** [comment]
I don't think that we would end up using blocktube, but we can add our own blocking method

**Comment by Trainerbob23** [comment]
> 

Oh ok, as long it blocks channel and videos. Thank you

**Comment by Trainerbob23** [comment]
Or uses a whitelist filter go ahead .
