### ISSUE TITLE
Allow links from YouTube to be able to be opened by Vuetube

### ISSUE THREAD

**Issue by CivilizedDeath** [Frontesque/VueTube#73]
Title says it all

**Comment by Frontesque** [comment]
This isn't very hard to do but requires the default YouTube app to be uninstalled or disabled.

**Comment by Rihcus** [comment]
> This isn't very hard to do but requires the default YouTube app to be uninstalled or disabled.

Not quite, all you need to do is disable open supported links in the primary youtube app and set vuetube to always open supported links.

An example with newpipe and stock youtube in Android 11:
![Screenshot_20220317-114018_Settings](https://user-images.githubusercontent.com/30292597/158837339-5452d485-8a0d-4439-8034-0c96aa9329f2.png)
![Screenshot_20220317-113858_Settings](https://user-images.githubusercontent.com/30292597/158837370-9e1ff702-0523-4853-a62e-62a8974ff8c0.png)

**Comment by 404-Program-not-found** [comment]
Closed. Added.
