### ISSUE TITLE
Scaling issue UI elements overlapping, search icons and three dot menu not centered

### ISSUE THREAD

**Issue by Whitedove99** [Frontesque/VueTube#76]
The bottom bar UI elements are overlapping for all three buttons (text and icon)

Search pane elements overlapping

Buttons in the search menu not centered (not sure if this is as intended)

**Screenshots**

![Screenshot_20220317-055413.png](https://user-images.githubusercontent.com/10663157/158813868-073c4608-7894-4ce8-b194-2e7cf1037acc.png)

![Screenshot_20220317-055431.png](https://user-images.githubusercontent.com/10663157/158813985-d0982071-6824-440a-9b40-ffb29f98caf6.png)

![Screenshot_20220317-055445.png](https://user-images.githubusercontent.com/10663157/158814010-fc3309be-49b0-40b1-8a96-57d40a61c3fa.png)
![Screenshot_20220317-055518.png](https://user-images.githubusercontent.com/10663157/158814035-6da79c8f-4c0e-4073-930d-a53c8a0ea6a1.png)

**Device Information**

App Information
App Version: 67ee6d9
Device Information
Platform: android
OS: android (11)
Model: Pixel 2 Manufacturer: Google Virtual: false

**Comment by Whitedove99** [comment]
> <img width="122" alt="Screen Shot 2022-03-17 at 3 46 26 PM" src="https://user-images.githubusercontent.com/31113245/158883454-d898d1b8-bb5b-4869-a071-e58c40be872f.png">
> I don't see the overlap, except for maybe like this.
> Is this what you mean @Whitedove99 ?

Ah yes that was it, also this is what I meant when I said "search pane elements overlapping" as I realize the issue wasn't visible in my other screenshot

![Screenshot_20220317-124752.png](https://user-images.githubusercontent.com/10663157/158884563-58600ed1-7abc-421d-87f2-565e3817a500.png)

So not quite overlapping but the button highlight is a few pixels away from the search bar

**Comment by Frontesque** [comment]
Fixed in PR [b85c6cb](https://github.com/Frontesque/VueTube/commit/b85c6cb309b6f06a7ba93f463ffba1422c06fda8)
