### ISSUE TITLE
Theme Resetting 

### ISSUE THREAD

**Issue by Nebula6531** [Frontesque/VueTube#8]
Upon full restarting the app, your theme resets

**Comment by NidPlays** [comment]
Also resets when  you click on something you have searched and so on

**Comment by Frontesque** [comment]
> 

im aware of that too

**Comment by Frontesque** [comment]
Working hard to find a solution

**Comment by Frontesque** [comment]
Update, The bug seems to have gotten worse over the past day:
Restarting the app causes some objects to retain the dark theme, such as white text, but other elements stay light theme (background) so some text becomes unreadable
