### ISSUE TITLE
[Android UI improvement] make the app go edge-to-edge

### ISSUE THREAD

**Issue by nokanol45** [Frontesque/VueTube#91]
# Problem

So the current UI looks like this:

light mode with navigation buttons
![VueTube_light_navbuttons_ (Small)](https://user-images.githubusercontent.com/101823676/158957317-96640bc0-9cbe-4075-958d-5509bb541de5.png)

dark mode with navigation buttons
![VueTube_dark_navbuttons (Small)](https://user-images.githubusercontent.com/101823676/158957399-0632b91b-b88c-4b3c-88b0-dc8edea7e76c.png)

light mode with gestures
![VueTube_light_gesture (Small)](https://user-images.githubusercontent.com/101823676/158957442-9e9ca91d-9113-49a3-82d4-4ff7c92dbbd1.png)

dark mode with gestures
![VueTube_dark_gesture (Small)](https://user-images.githubusercontent.com/101823676/158957469-26d44948-1caf-4043-8c00-02da5c84bc26.png)

See that black status bar and black navigation buttons/gesture background? That is the issue. In my opinion they don't look good. I think that they should be the same color as the elements next to them. So for example status bar in light mode would be red, and it would be gray in dark mode.

# Solution

Make the app go edge-to-edge!
Here's the android documentation for this:
https://developer.android.com/training/gestures/edge-to-edge

So after applying edge-to-edge, the app would look like this (mockups):

light mode with navigation buttons
![VueTube_light_navbutton_edgetoedgemockup (Small)](https://user-images.githubusercontent.com/101823676/158957584-a5907ba7-d19e-48f3-ba55-471c551ff4c3.png)

dark mode with navigation buttons
![VueTube_dark_navbutton_edgetoedgemockup (Small)](https://user-images.githubusercontent.com/101823676/158957600-c61acad1-c437-4252-80ec-fd8f6a3d40f6.png)

light mode with gestures
![VueTube_light_gesture_edgetoedgemockup (Small)](https://user-images.githubusercontent.com/101823676/158957632-14078225-f28d-432b-81f6-94a87ca72be1.png)

dark mode with gestures
![VueTube_dark_gesture_edgetoedgemockup (Small)](https://user-images.githubusercontent.com/101823676/158957646-c62a7021-6bdc-4ad3-a4ff-e99fefbf1eeb.png)

Much better, isn't it?

Aside from this, you could even do more stuff with edge-to-edge, like making the feed go full-screen, like the 3rd-party reddit app Infinity:
![Screenshot_20220318-154332_Infinity (Small)](https://user-images.githubusercontent.com/101823676/158958238-6657f2e1-8a8b-439b-8178-82542d250229.png)

... or maybe add some tasteful blur to the content behind the header like Telegram:
![tempFileForShare_20220318-154755](https://user-images.githubusercontent.com/101823676/158958942-269ec2ff-6d8a-4cd3-aaaf-b916f3338fad.png)

**Comment by nokanol45** [comment]
Not a dev, so take this with a MASSIVE grain of salt - 

Seems like the latest nightly implements status bar coloring (via @capacitor/status-bar if I'm correct), but it seems like the coloring will only apply after every relaunch of the app. It also doesn't fix the gesture bar background:

_This screenshot shows the app when it is relaunched with light mode on, then dark mode is selected. You can see the status bar is still red, and the background color for the gesture bar is still black._
![Screenshot_20220319-151849_VueTube](https://user-images.githubusercontent.com/101823676/159111784-9586ce97-6309-4584-a85c-b31d41c7a7c6.png)

Idk how you would do this with Vue, but ideally the general idea of a proper fix would be:

1. Allow the app to draw on the entire screen
2. Find out what the system insets are (using the terms from https://developer.android.com/training/gestures/edge-to-edge#nav-bar-overlap), so the width of the status bar, navigation buttons, gesture bar, etc.
3. Apply the appropriate padding to avoid overlapping with those items

Doing things this way allows freedom to do whatever you want with the space behind the system insets, as described in my original post.

Hopefully I'm clear enough on this.

**Comment by nokanol45** [comment]
I found this capacitor plugin called @capacitor/safe-area: https://github.com/capacitor-community/safe-area

Is it a viable fix to this and #110 or am I off on the wrong foot here?

**Comment by PickleNik** [comment]
@Frontesque I reassigned since this'll be fixed in my pr by applying theme to navbar and status bar
<img width="336" alt="Screen Shot 2022-03-31 at 9 40 57 AM" src="https://user-images.githubusercontent.com/31113245/161068666-ec6e8f06-3538-4f26-b568-ffb1105458b6.png">

**Comment by PickleNik** [comment]
> Not a dev, so take this with a MASSIVE grain of salt -
> 
> Seems like the latest nightly implements status bar coloring (via @capacitor/status-bar if I'm correct), but it seems like the coloring will only apply after every relaunch of the app. It also doesn't fix the gesture bar background:
> 
> _This screenshot shows the app when it is relaunched with light mode on, then dark mode is selected. You can see the status bar is still red, and the background color for the gesture bar is still black._ ![Screenshot_20220319-151849_VueTube](https://user-images.githubusercontent.com/101823676/159111784-9586ce97-6309-4584-a85c-b31d41c7a7c6.png)
> 
> Idk how you would do this with Vue, but ideally the general idea of a proper fix would be:
> 
> 1. Allow the app to draw on the entire screen
> 2. Find out what the system insets are (using the terms from https://developer.android.com/training/gestures/edge-to-edge#nav-bar-overlap), so the width of the status bar, navigation buttons, gesture bar, etc.
> 3. Apply the appropriate padding to avoid overlapping with those items
> 
> Doing things this way allows freedom to do whatever you want with the space behind the system insets, as described in my original post.
> 
> Hopefully I'm clear enough on this.

This is how iOS safearea works right now (on my fork) since iOS safearea is provided directly in CSS through `env()` idk if full-screening on Android is a good idea and whether it will work on all versions of Android

**Comment by PickleNik** [comment]
To be clear, with my fix it is still possible to full-screen the app in certain situations like for a player
