### ISSUE TITLE
Keyboard Enter to search not working

### ISSUE THREAD

**Issue by Wtcheesecakes** [Frontesque/VueTube#93]
**Describe the bug**
The enter key on the keyboard should allow for the same function as the search button

**To Reproduce**

1. Go to search
2. Type in search
3. Press enter and nothing will happen

**Expected behavior**
1. Go to search
2. Type in search
3. Press enter and search result should be retuned

**Screenshots**

**Device Information**
 - OS: Android 11
 - App Version: Latest github action build

**Additional context**

**Comment by DanWlker** [comment]
This should fix it

**Comment by Frontesque** [comment]
fixed in PR #115
