### ISSUE TITLE
Hangul Err


### ISSUE THREAD

**Issue by Sayori1576** [Frontesque/VueTube#94]
![Screenshot_20220318-235924_VueTube.jpg](https://user-images.githubusercontent.com/93511899/159027462-54f9f9d7-f5f3-4da8-94eb-cb92048061e0.jpg)![Screenshot_20220318-235938_VueTube.jpg](https://user-images.githubusercontent.com/93511899/159027474-0f2759b7-627b-4411-ba29-87084c60488b.jpg)
Only ? is printed

**Comment by 404-Program-not-found** [comment]
This seems to be similar to the error described in #62. Unicode compatibility appears to be an issue right now

**Comment by 404-Program-not-found** [comment]
fixed in #192. Closing
