### ISSUE TITLE
OLED dark mode switches to normal dark mode, LCD switches to OLED dark mode

### ISSUE THREAD

**Issue by Deathstalkr1** [Frontesque/VueTube#99]
**Describe the bug**
When you enable dark mode on vuetube, you have 2 choices. Either dark mode or oled dark mode. Switching to oled dark mode switches to normal dark mode, and lcd dark mode switches to oled dark mode.

**To Reproduce**
1. Have a samsung phone
2. Go to vuetube app
3. Click on dark mode
4. Find out that the dark modes are switched.

**Expected behavior**
The opposite of what I explained.

**Screenshots**
![Screenshot_20220318-172247_VueTube.jpg](https://user-images.githubusercontent.com/100892324/159085058-4315ed87-fdad-443c-8330-835bdadf7fd8.jpg)

![Screenshot_20220318-172243_VueTube.jpg](https://user-images.githubusercontent.com/100892324/159085072-a36b1e65-4345-41cf-82e2-11491cf004e8.jpg)

**Device Information**
 - OS: Android 12
 - App version: 1b6a9f4 
 - Device: Samsung SM-G998U

**Additional context**
None.

**Comment by Tosoju** [comment]
https://github.com/Frontesque/VueTube/issues/46

**Comment by DanWlker** [comment]
Not an inherent issue with the code. I guess a poll on the discord server could be done to see which one is better:

a) Text displayed is the current mode
or 
b) Text displayed is the mode that is going to be switched to.

**Comment by Frontesque** [comment]
On the latest unstable version, is this still an issue?

**Comment by PickleNik** [comment]
> On the latest unstable version, is this still an issue?

it is not

**Comment by PickleNik** [comment]
ight, I'll make the switch label more obvious
